import './globals.css'
import { Gothic_A1 } from 'next/font/google'

const font = Gothic_A1({ weight: ["400", "500", "700"], subsets: ["latin"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-background`}>{children}</body>
    </html>
  )
}
