export const formatDate = (dateObj: {
  seconds: string;
  nanoseconds: string;
}) => {
  const date = new Date(parseInt(dateObj.seconds) * 1000);

  //INFO: this is generated by chat gpt4, could be made better, but its still good enough
  const formattedDate = date.toLocaleString("pl-PL", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
  return formattedDate;
};
