export const usersMock = [
  {
    id: 3,
    avatar: "https://i.ibb.co/1T0bCkC/man.png",
    name: "Musharof Chowdhury",
    email: "musharos@example.com",
    aquariumTitle: "Multidisciplinary Web Entrepreneur",
    healthStatus: "Good",
    aquariumSize: "2m^3",
    isLiked: false,
  },
  {
    id: 5,
    avatar: "",
    name: "Nenifer Lofess",
    email: "loffes.cooper@example.com",
    aquariumTitle: "Regional Paradigm Technician",
    healthStatus: "Good",
    aquariumSize: "3m^3",
    isLiked: false,
  },
  {
    id: 7,
    avatar: "",
    name: "Jhon Smith",
    email: "jhon.smith@example.com",
    aquariumTitle: "Lead Implementation Liaison",
    healthStatus: "Bad",
    aquariumSize: "4m^3",
    isLiked: true,
  },
  {
    id: 8,
    avatar: "",
    name: "Suliym Info",
    email: "suliym.info@example.com",
    aquariumTitle: "Applications Engineer",
    healthStatus: "Bad",
    aquariumSize: "5m^3",
    isLiked: false,
  },
  {
    id: 9,
    avatar: "https://i.ibb.co/1T0bCkC/man.png",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: false,
  },
  {
    id: 11,
    avatar: "https://i.ibb.co/1T0bCkC/man.png",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: true,
  },
  {
    id: 10,
    avatar: "https://i.ibb.co/1T0bCkC/man.png",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: true,
  },
  {
    id: 12,
    avatar: "https://i.ibb.co/1T0bCkC/man.png",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: false,
  },
  {
    id: 13,
    avatar: "https://i.ibb.co/1T0bCkC/man.png",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: false,
  },
  {
    id: 14,
    avatar: "https://i.ibb.co/1T0bCkC/man.png",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: false,
  },
  {
    id: 18,
    avatar: "https://i.ibb.co/1T0bCkC/man.png",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: false,
  },
  {
    id: 16,
    avatar: "",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: false,
  },
  {
    id: 20,
    avatar: "https://i.ibb.co/1T0bCkC/man.png",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: false,
  },
  {
    id: 88,
    avatar: "https://i.ibb.co/1T0bCkC/man.png",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: false,
  },
  {
    id: 89,
    avatar: "https://i.ibb.co/1T0bCkC/man.png",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: false,
  },
  {
    id: 91,
    avatar: "",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: false,
  },
  {
    id: 92,
    avatar: "",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: false,
  },
  {
    id: 93,
    avatar: "https://i.ibb.co/1T0bCkC/man.png",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: false,
  },
  {
    id: 95,
    avatar: "https://i.ibb.co/1T0bCkC/man.png",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: false,
  },
  {
    id: 96,
    avatar: "",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: false,
  },
  {
    id: 98,
    avatar: "https://i.ibb.co/1T0bCkC/man.png",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: false,
  },
  {
    id: 99,
    avatar: "https://i.ibb.co/1T0bCkC/man.png",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: false,
  },
  {
    id: 101,
    avatar: "",
    name: "Lorem Ipsumiński",
    email: "lorem.ipsum@example.com",
    aquariumTitle: "Lorem Ipsum Guy",
    healthStatus: "Good",
    aquariumSize: "6m^3",
    isLiked: false,
  },
];

export const logsMock = [
  {
    id: 1,
    name: "AquaView",
    log: "Started following Mohamed's aquarium",
    date: "28.05.2023 15:00",
  },
  {
    id: 2,
    name: "AquaView",
    log: "Started following Mohamed's aquarium",
    date: "28.05.2023 15:31",
  },
  {
    id: 3,
    name: "AquaCreator",
    log: "Created MyNewAquarium aquarium",
    date: "28.05.2023 16:00",
  },
  {
    id: 4,
    name: "Some service",
    log: "something happened",
    date: "28.05.2023 17:31",
  },
  {
    id: 5,
    name: "some service",
    log: "something happened",
    date: "28.05.2023 18:51",
  },
];

export const aquaLifeItemsMock = [
  {
    id: 3,
    image: "",
    name: "Fish 1",
    description: "description of fish",
    size: "12-23 cm",
    environment: "Compatible",
  },
  {
    id: 6,
    image: "",
    name: "Fish 1",
    description: "description of fish",
    size: "12-23 cm",
    environment: "Not Compatible",
  },
  {
    id: 8,
    image: "",
    name: "Fish 1",
    description: "description of fish",
    size: "12-23 cm",
    environment: "Not Compatible",
  },
  {
    id: 20,
    image: "",
    name: "Fish 1",
    description: "description of fish",
    size: "12-23 cm",
    environment: "Compatible",
  },
  {
    id: 22,
    image: "",
    name: "Fish 1",
    description: "description of fish",
    size: "12-23 cm",
    environment: "Not Compatible",
  },
  {
    id: 25,
    image: "",
    name: "Fish 1",
    description: "description of fish",
    size: "12-23 cm",
    environment: "Compatible",
  },
  {
    id: 31,
    image: "",
    name: "Fish 1",
    description: "description of fish",
    size: "12-23 cm",
    environment: "Compatible",
  },
  {
    id: 32,
    image: "",
    name: "Fish 1",
    description: "description of fish",
    size: "12-23 cm",
    environment: "Compatible",
  },
  {
    id: 35,
    image: "",
    name: "Fish 1",
    description: "description of fish",
    size: "12-23 cm",
    environment: "Compatible",
  },
  {
    id: 45,
    image: "",
    name: "Fish 1",
    description: "description of fish",
    size: "12-23 cm",
    environment: "Compatible",
  },
  {
    id: 55,
    image: "",
    name: "Fish 1",
    description: "description of fish",
    size: "12-23 cm",
    environment: "Compatible",
  },
  {
    id: 100,
    image: "",
    name: "Fish 1",
    description: "description of fish",
    size: "12-23 cm",
    environment: "Compatible",
  },
  {
    id: 101,
    image: "",
    name: "Fish 1",
    description: "description of fish",
    size: "12-23 cm",
    environment: "Compatible",
  },
];
